---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: e2e-tests-image
  labels:
    app: 3scale-e2e-tests
spec:
  type: image
  params:
  - name: url
    value: quay.io/3scale/e2e-tests
