---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: status-report
  labels:
    app: 3scale-e2e-tests
spec:
#  no support for `volumeClaimTemplate` in 0.11.x
#  workspaces:
#    - name: results
#      description: The folder where we read the test results from
#      readOnly: true
  params:
    - name: tests_exit_status
      type: string
      description: The exit status of the e2e tests step

  steps:
    - name: status
      image: bash:latest
      script: |
        #!/usr/bin/env bash

        exit $(inputs.params.tests_exit_status)
