---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot-quay-git-ssh
  labels:
    app: qe-e2e-tests
secrets:
- name: git-ssh
- name: quay-readonly-credentials
- name: quay-rhmi-robot-readonly
imagePullSecrets:
- name: quay-readonly-credentials
- name: quay-rhmi-robot-readonly

