apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: e2e-tests-pipeline-listener
  name: e2e-tests-pipeline-route
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-e2e-tests-pipeline-listener
  tls:
    termination: edge